export { default as Map } from './Map.page'
export { default as MessagePage } from './Message.page'
export { default as PortfolioPage } from './Portfolio.page'
export { default as StockPage } from './Stock.page'
export { default as Test } from './Test.page'
export { default as VisitorPage } from './Visitor.page'
