export { default as Contact } from './Contact';
export { default as Footer } from './Footer';
export { default as Home } from './Home';
export { default as ListModal } from './ListModal';
export { default as Loading } from './Loading';
export { default as MapTest } from './MapTest';
export { default as StockTable } from './StockTable';
export { default as Test } from './Test';
export { default as Work } from './Work';
